# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc066ad83834b8f4737d5c5d110ef45fc0efe4174f4f14133dff21e12c5fb516b6875b6ddb5f540aa8ea10f3b812ce9863d2db9386ab18d1de1822db8f0257fb

test:
  secret_key_base: a26b7fb1dbbb1f5f81eac083254a596f90345c23439d8a29fa4757bf11dd9382ad533a0c4de2044b1f1f254b4b7c554ea49d95d141fe0cb7567c88e96ac6498f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
